# Site settings

title: YOV
email: boretskyi@yov.com.ua
description: Могилянська колективна платформа
keywords: yov, могилянка, наукма, кма, брюховецький, квіт, мелешевич, студенти, спудеї, йов, іов, борецький, naukma, kma, академія, могилянська, могилянський, вісник, бонет, плацераці
baseurl: ""
url: "http://yov.com.ua"
email: boretskyi@yov.com.ua
twitter_username: yov_boretskiy
facebook_username: yovkma
github_username: boretskyi
facebook_app_id: 633629610107763

collections:
- events

# Navigation

navigation:
- text: "Вісник"
  url: /journal/
  landing: true
  layout: journal

- text: "Навколо"
  url: /calendar/
  landing: true

- text: "Друзі"
  url: /friends/
  landing: true

- text: "Про&nbsp;нас"
  url: /about/
  landing: true

- text: "+&nbsp;Написати"
  url: /write/
  landing: false

# Blog
featured_count: 1

# Build settings
markdown: kramdown
paginate: 5
paginate_path: /journal/:num
permalink: /journal/:year/:month/:day/:title/
sass:
    style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate


# Prose.io
prose:
  siteurl: "http://yov.com.ua"
  rooturl: "_posts"
  media: 'media'
  ignore:
    - /journal
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "textarea"
          label: "Title"
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured"
          value: false
      - name: "author"
        field:
          element: "text"
          label: "Author"
      - name: "author_link"
        field:
          element: "text"
          label: "Author link"
          help: "Link to author's website or page"
          placeholder: "http://facebook.com/username"
      - name: "author_facebook_profile"
        field:
          element: "text"
          label: "Author facebook profile"
          help: "Fill this if author's link is not a facebook profile"
          placeholder: "http://facebook.com/username"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "image"
        field:
          element: "text"
          label: "Background image"
          placeholder: "/media/image.jpg"
      - name: "thumbnail"
        field:
          element: "text"
          label: "Opengraph (Facebook) thumbnail image"
          placeholder: "/media/image.jpg"
      - name: "thumbnail_width"
        field:
          element: "text"
          label: "Thumbnail image width, in pixels"
          placeholder: "1600"
      - name: "thumbnail_height"
        field:
          element: "text"
          label: "Thumbnail image height, in pixels"
          placeholder: "1000"
      - name: "image_credit"
        field:
          element: "text"
          placeholder: "Reuters"
          label: "Image credit"
          help: "Author or source of the image"
          value: null
      - name: "image_credit_link"
        field:
          element: "text"
          placeholder: "http://reuters.com"
          label: "Image credit link"
          help: "Link to image source or author"
          value: null
      - name: "fotorama"
        field:
          element: "checkbox"
          label: "Fotorama"
          help: "Enable fotorama image slideshows"
          value: false
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          placeholder: "Choose categories"
          options:
            - name: "Культура"
              value: "culture"
            - name: "Суспільство"
              value: "community"
            - name: "Наука"
              value: "science"
